---
functional:
  - Возможность соревноваться двум игрокам в решении задач с отображением кода друг друга
  - Возможность играть с ботом
  - Возможность играть с другом по ссылке
  - Возможность выбора задачи по уровню сложности
  - Возможность выбора языка программирования
  - Возможность сброса решения до шаблонного (Reset solution)
  - Возможность переключения между вкладками TASK и OUTPUT
  - Возможность повторного запуска игры (Try again)
  - Возможность продолжить текущую игру (Continue)
  - Возможность просмотра других игр (Show)
  - Возможность общения в общем чате и в личных сообщениях
  - Возможность отправки приглашения на дуэль
  - Возможность создания турнира и участия в нем
  - Возможность просмотра лидерборда (за неделю, месяц, всё время)
  - Возможность управления профилем, настройками, задачами и турнирами
  - Возможность восстановления пароля по email
  - Возможность входа/регистрация с помощью Email, GitHub и Discord

non-functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным для использования на мобильных устройствах
  - Сайт должен быть способен обрабатывать до 1000 одновременных пользователей

implicit:
  - Сайт должен быть безопасным и защищать пользовательские данные
  - Пользовательский интерфейс должен быть интуитивно понятным и удобным
