---
functional:
  - Возможность соревноваться двум игрокам в решении задач с отображением кода
    друг друга
  - Возможность играть с ботом или с другом по ссылке
non-functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть удобным для использования на мобильных устройствах
  - Сайт должен быть способен обрабатывать до 1000 одновременных пользователей
implicit:
  - Сайт должен быть безопасным и защищать пользовательские данные
  - Пользовательский интерфейс должен быть интуитивно понятным и удобным