---
functional:
  - Возможность соревноваться двум игрокам в решении задач с отображением кода друг друга
  - Возможность играть с ботом
  - Возможность играть с другом по ссылке
  - Невозможно играть с рандомами
  - Возможность выбора задачи по уровню сложности
  - Возможность смены языка программирования во время решения задачи, а не на этапе создания игры
  - Возможность сброса решения до шаблонного (Reset solution)
  - Возможность переключения между вкладками TASK и OUTPUT
  - Возможность повторного запуска игры (Try again)
  - Возможность продолжить текущую игру (Continue)
  - Возможность просматривать текущую игру других игроков через кнопку "Show" во вкладке Lobby
  - Возможность просматривать завершённую игру через кнопку "Show" во вкладке History
  - Возможность общения в общем чате и в личных сообщениях
  - Возможность отправки приглашения на дуэль
  - Возможность создавать свои игры
  - Возможность создания турнира и участия в нем
  - Возможность просмотра лидерборда (за неделю, месяц, всё время)
  - Возможность управления профилем, настройками, задачами и турнирами
  - Возможность восстановления пароля по email
  - Пользователь должен иметь возможность выйти из своей учетной записи
  - Возможность входа/регистрация с помощью Email, GitHub и Discord

non-functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным для использования на мобильных устройствах
  - Сайт должен быть способен обрабатывать до 1000 одновременных пользователей

implicit:
  - Сайт должен быть безопасным и защищать пользовательские данные
  - Пользовательский интерфейс должен быть интуитивно понятным и удобным
    
    foreach (str_split((string)$i) as $digit) {
    $sum += (int)$digit;
    }